import yaml
from pprint import pprint

target_dict = { 'get_bgp_neighbors': { 'global': { 'peers': { '10.10.10.102': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': 5,
                                                                                                        'received_prefixes': 5,
                                                                                                        'sent_prefixes': 5}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': True,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '2.2.2.2',
                                                                  'uptime': 25192},
                                                '10.10.10.103': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': 0,
                                                                                                        'received_prefixes': 0,
                                                                                                        'sent_prefixes': 5}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': True,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '3.3.3.3',
                                                                  'uptime': 19256},
                                                '10.10.10.104': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': 6,
                                                                                                        'received_prefixes': 6,
                                                                                                        'sent_prefixes': 5}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': True,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '4.4.4.4',
                                                                  'uptime': 25173},
                                                '10.10.10.105': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': 4,
                                                                                                        'received_prefixes': 4,
                                                                                                        'sent_prefixes': 5}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': True,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '5.5.5.5',
                                                                  'uptime': 25208},
                                                '10.10.10.106': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': 4,
                                                                                                        'received_prefixes': 4,
                                                                                                        'sent_prefixes': 5}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': True,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '6.6.6.6',
                                                                  'uptime': 25198},
                                                '10.10.10.107': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': 4,
                                                                                                        'received_prefixes': 4,
                                                                                                        'sent_prefixes': 5}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': True,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '7.7.7.7',
                                                                  'uptime': 25210},
                                                '10.10.10.108': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': 5,
                                                                                                        'received_prefixes': 5,
                                                                                                        'sent_prefixes': 5}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': True,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '8.8.8.8',
                                                                  'uptime': 25215},
                                                '10.10.10.109': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': -1,
                                                                                                        'received_prefixes': -1,
                                                                                                        'sent_prefixes': -1}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': False,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '0.0.0.0',
                                                                  'uptime': -1},
                                                '10.10.10.110': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': -1,
                                                                                                        'received_prefixes': -1,
                                                                                                        'sent_prefixes': -1}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': False,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '0.0.0.0',
                                                                  'uptime': -1},
                                                '10.10.10.111': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': -1,
                                                                                                        'received_prefixes': -1,
                                                                                                        'sent_prefixes': -1}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': False,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '0.0.0.0',
                                                                  'uptime': -1},
                                                '10.10.10.112': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': 5,
                                                                                                        'received_prefixes': 5,
                                                                                                        'sent_prefixes': 5}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': True,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '12.12.12.12',
                                                                  'uptime': 25059},
                                                '10.10.10.113': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': 5,
                                                                                                        'received_prefixes': 5,
                                                                                                        'sent_prefixes': 5}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': True,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '13.13.13.13',
                                                                  'uptime': 25064},
                                                '10.10.10.198': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': -1,
                                                                                                        'received_prefixes': -1,
                                                                                                        'sent_prefixes': -1}},
                                                                  'description': '',
                                                                  'is_enabled': True,
                                                                  'is_up': False,
                                                                  'local_as': 65001,
                                                                  'remote_as': 65001,
                                                                  'remote_id': '0.0.0.0',
                                                                  'uptime': -1},
                                                '185.10.10.254': { 'address_family': { 'ipv4 unicast': { 'accepted_prefixes': 0,
                                                                                                         'received_prefixes': 0,
                                                                                                         'sent_prefixes': 26}},
                                                                   'description': '',
                                                                   'is_enabled': True,
                                                                   'is_up': True,
                                                                   'local_as': 65001,
                                                                   'remote_as': 6519,
                                                                   'remote_id': '14.14.14.14',
                                                                   'uptime': 24781}},
                                     'router_id': '1.1.1.1'}}}
                                     
filename = "validate_BGP_R1.yaml"
with open(filename, "w") as f:
    output = yaml.dump(target_dict, f, default_flow_style=False)
