OSPF: 
    process_id: "1"
    rid: "12.12.12.12"
    redistributing:
        - "connected subnets"
        - "eigrp 100 subnets"
    networks:
        - "27.27.27.0 area 0"
        - "56.56.56.0 area 0"