OSPF: 
    process_id: "1"
    rid: "4.4.4.4"
    redistributing:
        - "connected subnets"
        - "eigrp 100 subnets"
    networks:
        - "19.19.19.0 area 0"
        - "21.21.21.0 area 0"
        - "24.24.24.0 area 0"