---
snmp:
    snmp_community: "gh-lab"

ospf:
    ospf_rid: 1.1.1.1
    ospf_process: "1"
    ospf_networks:
        - net: "0.0.0.0"
          wildcard: "255.255.255.255"
          area: 0
        - net: 10.10.10.0
          mask: 0.0.0.255
          area: 0
    vrfs:
        - name: "test"
          rd: "65001:1"


bgp:
   asn: "65001"
   rid: 1.1.1.1
   update_source: "loopback0"
   route_reflector: False
   neighbors:
       - 3.3.3.3
       - 4.4.4.4
        
loopback0: "1.1.1.1"
